### ISSUE TITLE
timeout can be configured by query metrics?

### ISSUE THREAD

**Issue by oscarvesga** [iamseth/oracledb_exporter#150]
Hello, I need make scraping each 5 or 10 seconds and the default metrics are taken more time, so I would like to know if each query metrics may be can configured with its own timeout?

**Comment by Yannig** [comment]
The master branch metric definition files are much more optimized from before. Maybe you could take a look. Another solution would be to delete requests that are taking too long so that the collection is as fast as possible by editing the toml file.

For the definition of a timeout, this adjustment can only be done globally. Adding a metric setting shouldn't be too much effort, but I think it's still a good idea to keep a global setting.
