### ISSUE TITLE
Documentation for User Account

### ISSUE THREAD

**Issue by domeger** [iamseth/oracledb_exporter#172]
Can someone document what type of permission level and access is needed to get the exporter ?

**Comment by mrjimroll** [comment]
Please, clarify your question in more details
What permissions are you asking about?

**Comment by billabongrob** [comment]
I think I understand the question.  It sounds like if you wanted to limit a specific users access in order to run this and not use the SYS, or overprivileged accounts, to make queries, what grants would be needed.  I'll try to update the readme with an example of how we're doing this.  @domeger  if this is not what your looking for, update the issue please.

**Comment by Yannig** [comment]
I don't know what to do exactly but I think you can try to use the following documentation: https://labs.consol.de/nagios/check_oracle_health/

I guess, you can try to create a user with the following privileges:

```sql
create user promexporter identified by oradbmon;
grant create session to promexporter;
grant select any dictionary to promexporter;
grant select on V_$SYSSTAT to promexporter;
grant select on V_$INSTANCE to promexporter;
grant select on V_$LOG to promexporter;
grant select on SYS.DBA_DATA_FILES to promexporter;
grant select on SYS.DBA_FREE_SPACE to promexporter;
```

**Comment by domeger** [comment]
@Yannig - Thanks, that is what I was looking for in my environment.
