### ISSUE TITLE
Unable to convert current value to float 

### ISSUE THREAD

**Issue by Cuigeek** [iamseth/oracledb_exporter#93]
ERRO[0402] Unable to convert current value to float (metric=limit_value,metricHelp=Generic counter metric from v$resource_limit view in Oracle (limit value).,value=< UNLIMITED>)  source=main.go:245
ERRO[0402] Unable to convert current value to float (metric=limit_value,metricHelp=Generic counter metric from v$resource_limit view in Oracle (limit value).,value=< UNLIMITED>)  source=main.go:245

**Comment by Yannig** [comment]
Hello there,

I am a human being and I am not paid to maintain this project.

Could you make an effort to describe your problem? Could you also say hello, excuse me, I have a problem that happens when I do [...] so I get [...] but I want to have [...].

To point on the right direction for you problem (I guess), I think you can try to use the last version of default-metrics.toml available here:

https://github.com/iamseth/oracledb_exporter/blob/master/default-metrics.toml

And have a nice day
